#pragma once

/* A 32-byte cycle stays in tune up to A5. A#5–C6 use a 16-byte cycle. */
#define SYNTH_WAVE_LEN 32
#define SYNTH_PAULA_CLOCK 3546895UL
#define SYNTH_MIN_PERIOD 124
#define SYNTH_MAX_VOLUME 64
#define SYNTH_AMPLITUDE 110

/* MIDI note 24 is C1. 61 notes reach C6. */
#define SYNTH_NOTE_FIRST 24
#define SYNTH_NOTE_COUNT 61

#define SEQUENCER_STEPS 16
#define SEQUENCER_BPM_MIN 40
#define SEQUENCER_BPM_MAX 240
#define SEQUENCER_BPM_DEFAULT 120

#define SEQ_STEP_PITCH (SCREEN_WIDTH / SEQUENCER_STEPS)
#define SEQ_GRID_TOP 4
#define SEQ_GRID_BOTTOM 176
#define SEQ_REST_TOP (SEQ_GRID_BOTTOM - 16)
#define SEQ_ICON_Y 182
#define SEQ_TAB_TOP 188
#define SEQ_TAB_BOTTOM 205
#define SEQ_TAB_SEQ_LEFT 2
#define SEQ_TAB_SEQ_RIGHT 46
#define SEQ_TAB_DRAW_LEFT 50
#define SEQ_TAB_DRAW_RIGHT 104
#define SEQ_TAB_SYNTH_LEFT 108
#define SEQ_TAB_SYNTH_RIGHT 154
#define SEQ_TAB_PRESET_LEFT 158
#define SEQ_TAB_PRESET_RIGHT 210
#define SEQ_WAVE_MODE_LEFT 214
#define SEQ_WAVE_MODE_RIGHT 268
#define SEQ_DUR_LEFT 272
#define SEQ_DUR_RIGHT 318
#define SYNTH_ROW1_COLUMNS 9
#define SYNTH_ROW2_COLUMNS 7
#define SYNTH_ROW3_COLUMNS 6
#define SYNTH_ROW1_TOP 2
#define SYNTH_ROW1_BOTTOM 62
#define SYNTH_ROW1_TRACK_TOP 22
#define SYNTH_ROW1_TRACK_BOTTOM 58
#define SYNTH_SEMI_TRACK_BOTTOM 44
#define SYNTH_SEMI_BUTTON_TOP 46
#define SYNTH_SEMI_BUTTON_BOTTOM 60
#define SYNTH_OSC_BUTTON_BOTTOM 44
#define SYNTH_GATE_TOP 46
#define SYNTH_ROW2_TOP 64
#define SYNTH_ROW2_BOTTOM 124
#define SYNTH_ROW2_TRACK_TOP 76
#define SYNTH_ROW2_TRACK_BOTTOM 120
#define SYNTH_ROW3_TOP 126
#define SYNTH_ROW3_BOTTOM (SEQ_TAB_TOP - 2)
#define SYNTH_ROW3_TRACK_TOP 138
#define SYNTH_ROW3_TRACK_BOTTOM (SYNTH_ROW3_BOTTOM - 4)
#define SYNTH_PANE_TOP SYNTH_ROW1_TOP
#define SYNTH_PANE_BOTTOM SYNTH_ROW3_BOTTOM
#define DRAW_LEFT 2
#define DRAW_RIGHT (SCREEN_WIDTH - 2)
#define DRAW_PLOT_LEFT 14
#define DRAW_PLOT_RIGHT (SCREEN_WIDTH - 8)
#define DRAW_TOP SEQ_GRID_TOP
#define DRAW_BOTTOM (SEQ_TAB_TOP - 2)
#define SEQ_PLAY_RIGHT 40
#define SEQ_TEMPO_TOP 206
#define SEQ_TEMPO_BOTTOM 242
#define SEQ_TEMPO_MINUS_LEFT (SEQ_PLAY_RIGHT + 6)
#define SEQ_TEMPO_MINUS_RIGHT 74
#define SEQ_TEMPO_BOX_LEFT 78
#define SEQ_TEMPO_BOX_RIGHT 118
#define SEQ_TEMPO_PLUS_LEFT 122
#define SEQ_TEMPO_PLUS_RIGHT 146
#define SEQ_OCTAVE_LEFT 150
#define SEQ_OCTAVE_RIGHT 180
#define SEQ_RANDOM_LEFT 184
#define SEQ_RANDOM_RIGHT 214
#define SEQ_LENGTH_LEFT 218
#define SEQ_LENGTH_RIGHT 284
#define SEQ_EXIT_LEFT 288
#define SEQ_EXIT_RIGHT 318

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 256
#define SCREEN_BYTES ((SCREEN_WIDTH / 8) * SCREEN_HEIGHT)
